### ISSUE TITLE
[BUG]: Spawns are way too reduced compared to what users expect.

### ISSUE THREAD

**Issue by ncottrill** [AreYSerious/betterruins#25]
### Mod Version

0.2.0

### Game Version

v1.18.6-rc.1

### Platform

Windows

### SP/MP

Multiplayer

### Description

I really don't like how much the spawns were reduced. Totally bummed. And, I'm not seeing the big ruins that are cool like the fortress (plaster with red roof) and others like it.

I tried increasing with the structures spawn mod ... doesn't change the problem.

### Logs

```Log```

**Comment by AreYSerious** [comment]
The spawn chances got halved for most ruins so with the Addon mod you should be able to increase the spawnchances more.

I will do some more testing on it tomorrow.

Are you using non default worldgen settings?
I'm hilly terrain ruins don't really like to spawn.

**Comment by AreYSerious** [comment]
The big ruins spawn every 5000 blocks this hasn't changed tho so they are quite rare.

**Comment by AreYSerious** [comment]
If you need more percentage for the Addon mod I can add a 400% and 500% mod but will find out tomorrow

**Comment by ncottrill** [comment]
Thanks for checking! So (Jade here), I tried the structure spawn chance increase mod and didn't notice a difference. We are running close to default world. I think I might've decreased how craggy the world could be. Like, our world is smoother than default.

**Comment by ncottrill** [comment]
What was the motivation behind changing the spawn rate? We had fun with it as it was. :) Hehe.

**Comment by ncottrill** [comment]
Hi again. Here are the settings. 
![image](https://github.com/AreYSerious/betterruins/assets/14022160/ace76b87-ac5b-40e0-828f-e301a19a79a0)
