### ISSUE TITLE
[BALANCE] Underground spawnchances too high

### ISSUE THREAD

**Issue by digital-r** [AreYSerious/betterruins#27]
### Mod Version

0.20

### Game Version

1.18.5

### Platform

Windows

### SP/MP

Multiplayer

### Description

Underground dungeon type ruins spawns too frequently

### How to reproduce

It is not first time, when i find big underground dungeons in very close proximity. Sometimes they can be found in one chunk column, but on different height.
 

### Logs

```Log```

**Comment by AreYSerious** [comment]
Your feedback is very welcome this will go into the next version with slightly reduced underground spawnchances.

In the meantime:

If you want to configure it for your playstyle try this mod:
https://mods.vintagestory.at/strspawnchances

**Comment by AreYSerious** [comment]
will do slight balance for betterruins with lower underground spawnrate
https://github.com/AreYSerious/betterruins/commit/0a1cad341e05e844392e9a0672899d8d37e301d9

**Comment by AreYSerious** [comment]
Fixed with 0.2.1
