### ISSUE TITLE
[BUG]: Missing materials (1.18.6)

### ISSUE THREAD

**Issue by WickedSchnitzel** [AreYSerious/betterruins#29]
### Mod Version

0.2.0

### Game Version

1.18.6

### Platform

Windows

### SP/MP

Singleplayer

### Description

Did not test with BR version 0.2.1 yet, so this may be obsolete.

3.7.2023 12:02:58 [Warning] Block schematic file worldgen/schematics/underground/underground-rare/samgrey-underground-rare-1-claystone.json uses blocks that could no longer be found. These will turn into air blocks! (affected: game:quern-claystone)
3.7.2023 12:02:58 [Warning] Block schematic file worldgen/schematics/underground/underground-rare/samgrey-underground-rare-1-limestone.json uses blocks that could no longer be found. These will turn into air blocks! (affected: game:quern-limestone)
3.7.2023 12:02:58 [Warning] Block schematic file worldgen/schematics/underground/underground-rare/samgrey-underground-rare-1-sandstone.json uses blocks that could no longer be found. These will turn into air blocks! (affected: game:quern-sandstone)
3.7.2023 12:02:58 [Warning] Block schematic file worldgen/schematics/underground/underground-rare/samgrey-underground-rare-1-slate.json uses blocks that could no longer be found. These will turn into air blocks! (affected: game:quern-slate)
3.7.2023 12:02:59 [Warning] Block schematic file worldgen/schematics/underground/underground-translocator-uncommon/dampusunderground-1-claystone.json uses items that could no longer be found. These will turn into unknown items! (affected: game:crystalizedore-rich-cassiterite-claystone)
3.7.2023 12:02:59 [Warning] Block schematic file worldgen/schematics/underground/underground-translocator-uncommon/dampusunderground-1-claystone.json uses items that could no longer be found. These will turn into unknown items! (affected: game:crystalizedore-rich-cassiterite-claystone)
3.7.2023 12:02:59 [Warning] Block schematic file worldgen/schematics/underground/underground-translocator-uncommon/dampusunderground-1-claystone.json uses items that could no longer be found. These will turn into unknown items! (affected: game:crystalizedore-rich-cassiterite-claystone)
3.7.2023 12:02:59 [Warning] Block schematic file worldgen/schematics/underground/underground-translocator-uncommon/dampusunderground-1-claystone.json uses items that could no longer be found. These will turn into unknown items! (affected: game:crystalizedore-rich-cassiterite-claystone)
3.7.2023 12:02:59 [Warning] Block schematic file worldgen/schematics/underground/underground-translocator-uncommon/dampusunderground-1-limestone.json uses items that could no longer be found. These will turn into unknown items! (affected: game:crystalizedore-rich-cassiterite-limestone)
3.7.2023 12:02:59 [Warning] Block schematic file worldgen/schematics/underground/underground-translocator-uncommon/dampusunderground-1-limestone.json uses items that could no longer be found. These will turn into unknown items! (affected: game:crystalizedore-rich-cassiterite-limestone)
3.7.2023 12:02:59 [Warning] Block schematic file worldgen/schematics/underground/underground-translocator-uncommon/dampusunderground-1-limestone.json uses items that could no longer be found. These will turn into unknown items! (affected: game:crystalizedore-rich-cassiterite-limestone)
3.7.2023 12:02:59 [Warning] Block schematic file worldgen/schematics/underground/underground-translocator-uncommon/dampusunderground-1-limestone.json uses items that could no longer be found. These will turn into unknown items! (affected: game:crystalizedore-rich-cassiterite-limestone)
3.7.2023 12:02:59 [Warning] Block schematic file worldgen/schematics/underground/underground-translocator-uncommon/dampusunderground-1-peridotite.json uses items that could no longer be found. These will turn into unknown items! (affected: game:crystalizedore-rich-cassiterite-peridotite)
3.7.2023 12:02:59 [Warning] Block schematic file worldgen/schematics/underground/underground-translocator-uncommon/dampusunderground-1-peridotite.json uses items that could no longer be found. These will turn into unknown items! (affected: game:crystalizedore-rich-cassiterite-peridotite)
3.7.2023 12:02:59 [Warning] Block schematic file worldgen/schematics/underground/underground-translocator-uncommon/dampusunderground-1-peridotite.json uses items that could no longer be found. These will turn into unknown items! (affected: game:crystalizedore-rich-cassiterite-peridotite)
3.7.2023 12:02:59 [Warning] Block schematic file worldgen/schematics/underground/underground-translocator-uncommon/dampusunderground-1-peridotite.json uses items that could no longer be found. These will turn into unknown items! (affected: game:crystalizedore-rich-cassiterite-peridotite)
3.7.2023 12:02:59 [Warning] Block schematic file worldgen/schematics/underground/underground-translocator-uncommon/dampusunderground-1-sandstone.json uses items that could no longer be found. These will turn into unknown items! (affected: game:crystalizedore-rich-cassiterite-sandstone)
3.7.2023 12:02:59 [Warning] Block schematic file worldgen/schematics/underground/underground-translocator-uncommon/dampusunderground-1-sandstone.json uses items that could no longer be found. These will turn into unknown items! (affected: game:crystalizedore-rich-cassiterite-sandstone)
3.7.2023 12:02:59 [Warning] Block schematic file worldgen/schematics/underground/underground-translocator-uncommon/dampusunderground-1-sandstone.json uses items that could no longer be found. These will turn into unknown items! (affected: game:crystalizedore-rich-cassiterite-sandstone)
3.7.2023 12:02:59 [Warning] Block schematic file worldgen/schematics/underground/underground-translocator-uncommon/dampusunderground-1-sandstone.json uses items that could no longer be found. These will turn into unknown items! (affected: game:crystalizedore-rich-cassiterite-sandstone)
3.7.2023 12:02:59 [Warning] Block schematic file worldgen/schematics/underground/underground-translocator-uncommon/dampusunderground-1-slate.json uses items that could no longer be found. These will turn into unknown items! (affected: game:crystalizedore-rich-cassiterite-slate)
3.7.2023 12:02:59 [Warning] Block schematic file worldgen/schematics/underground/underground-translocator-uncommon/dampusunderground-1-slate.json uses items that could no longer be found. These will turn into unknown items! (affected: game:crystalizedore-rich-cassiterite-slate)
3.7.2023 12:02:59 [Warning] Block schematic file worldgen/schematics/underground/underground-translocator-uncommon/dampusunderground-1-slate.json uses items that could no longer be found. These will turn into unknown items! (affected: game:crystalizedore-rich-cassiterite-slate)
3.7.2023 12:02:59 [Warning] Block schematic file worldgen/schematics/underground/underground-translocator-uncommon/dampusunderground-1-slate.json uses items that could no longer be found. These will turn into unknown items! (affected: game:crystalizedore-rich-cassiterite-slate)

### Logs

```Log```

**Comment by AreYSerious** [comment]
https://github.com/AreYSerious/betterruins/issues/26

Fixed since 0.2.1
