### ISSUE TITLE
Stone variants for ruins

### ISSUE THREAD

**Issue by Fireztonez** [AreYSerious/betterruins#3]
> Atm vanilla lets you only do this to underground structures and not to the ones at the surface. I messaged with a dev they are going to take a look at the whole system. (in the next weeks or 1.18)(1.18 is more likely)

Okay, so in that case I guess I would just create some variants of some structures for some nice looking common rock type, just to add some variety, without overcharging the mod with soo much doubled structures

**So maybe:**
- Sandstone
- Claystone
- Andesite
- Basalt
- Shale

Can just add 1 or 2 variants by structures maybe something like that.

Just be sure if you add more structures in the world that the total amount of structure generated stay about the same, to not overload the world with soo many different ruins.

**Comment by AreYSerious** [comment]
![2022-08-29_20-03-48](https://user-images.githubusercontent.com/100879715/187268217-adcba666-e415-43c5-a608-a693a1b5e6bb.png)

**Comment by AreYSerious** [comment]
Thanks fixed with v0.0.2
