### ISSUE TITLE
[BUG]: Unable to craft Cupronickel Nails and Strips

### ISSUE THREAD

**Issue by Illun3** [AreYSerious/betterruins#48]
### Mod Version

v0.3.9

### Game Version

v1.19.8

### Platform

Windows

### SP/MP

Multiplayer

### Description

Unable to craft Cupronickel Nails and Strips 1.9

### How to reproduce

1) Make Cupnik Ingot
2) Cant make Strips

### Screenshots

![Bugreport](https://github.com/user-attachments/assets/8b225865-e316-4d68-9801-704879c36091)

### Logs

```Log```

**Comment by AreYSerious** [comment]
Thank you very much for the report.

I already fixed it for the next update that is out soon.

https://github.com/AreYSerious/betterruins/commit/57e3134d35d8a5442e59121920e9993d72dc1e2a
