### ISSUE TITLE
[BUG]: Crashes during University Ruins exploration

### ISSUE THREAD

**Issue by percussigant** [AreYSerious/betterruins#51]
### Mod Version

o.4.1

### Game Version

v1.20.rc5

### Platform

Windows

### SP/MP

Multiplayer

### Description

Crashes exploring the University ruin running a variety of other mods

### Logs

```Log```
Client Side: 
18/12/2024 17:34:22: Critical error occurredLoaded Mods: advancedsmithing@1.3.0, aged@1.0.6, ancientarmory@1.0.6, arrowheadsrecovery@1.0.1, bettercrates@1.8.0-rc.4, betterloot@1.0.2, scrapblocks@1.1.0, bettershears@1.0.0, brickmold@1.2.0, canoemod@1.0.2, chiseltools@1.14.3, claycasting@1.2.2, darcesdrifters@1.0.0, easyelk@1.0.0, extrachests@1.8.0, hideplayername@2.1.1, liberatedbeds@1.0.0, longtermfood@0.0.7, millwright@1.1.8, molds@0.1.3, nailsmold@1.0.2, oils@1.2.3, primitivesurvival@3.7.4, sortablestorage@2.2.8, temporal_gears_stack@1.0.0, terraprety@5.0.5, translocatorengineeringredux@1.5.4, game@1.20.0-rc.5, zoombuttonreborn@2.0.0, alchemy@1.6.41, animalcages@3.0.3, apegrapes@1.1.3, egocaribautomapmarkers@4.0.0, barreldough@2.0.0, betterfirepit@1.1.4, betterhewnfencegates@1.1.0, betterruins@0.4.1, butchering@1.7.3, carryon@1.7.4, commonlib@2.6.1, cooperativecombat@1.1.1, Crateful@1.2.8, danacancook@0.2.4, danatweaks@3.3.7, farmlanddropssoil@1.4.0, foodshelves@1.4.4, fromgoldencombs@1.8.1, gourmand@1.2.6, labeledtrunk@1.0.5, mobsradar@2.1.2, playerlist@2.1.4, claywheel@1.1.2, prospecttogether@1.4.0, rivers@3.2.0, scarecrow@1.6.1, stepupcontinued@0.0.1, usefulstuff17patch@1.0.0, stonebakeoven@1.1.4, storagecontroller@1.1.2, vanity@2.2.1, creative@1.20.0-rc.5, vsimgui@1.1.5, survival@1.20.0-rc.5, waypointtogether@1.0.1, wildfarmingrevival@1.2.9, configlib@1.3.13, helvehammerext@1.7.0, playercorpse@1.11.0, stonequarry@3.4.2, thriftysmithing@1.2.0System.NullReferenceException: Object reference not set to an instance of an object.   at Vintagestory.API.Common.ClientAnimator.calculateMatrices(Single dt) in VintagestoryApi\Common\Model\Animation\ClientAnimator.cs:line 294   at Vintagestory.Client.NoObf.SystemRenderEntities.OnBeforeRender(Single dt) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 49   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 188   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 824   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 161   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 695   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 670   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 92   at OpenTK.Windowing.Desktop.GameWindow.Run()   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 334   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Game Version: v1.20.0-rc.5 (Unstable)18/12/2024 17:37:31: Critical error occurredLoaded Mods: advancedsmithing@1.3.0, aged@1.0.6, ancientarmory@1.0.6, arrowheadsrecovery@1.0.1, bettercrates@1.8.0-rc.4, betterloot@1.0.2, scrapblocks@1.1.0, bettershears@1.0.0, brickmold@1.2.0, canoemod@1.0.2, chiseltools@1.14.3, claycasting@1.2.2, darcesdrifters@1.0.0, easyelk@1.0.0, extrachests@1.8.0, hideplayername@2.1.1, liberatedbeds@1.0.0, longtermfood@0.0.7, millwright@1.1.8, molds@0.1.3, nailsmold@1.0.2, oils@1.2.3, primitivesurvival@3.7.4, sortablestorage@2.2.8, temporal_gears_stack@1.0.0, terraprety@5.0.5, translocatorengineeringredux@1.5.4, game@1.20.0-rc.5, zoombuttonreborn@2.0.0, alchemy@1.6.41, animalcages@3.0.3, apegrapes@1.1.3, egocaribautomapmarkers@4.0.0, barreldough@2.0.0, betterfirepit@1.1.4, betterhewnfencegates@1.1.0, betterruins@0.4.1, butchering@1.7.3, carryon@1.7.4, commonlib@2.6.1, cooperativecombat@1.1.1, Crateful@1.2.8, danacancook@0.2.4, danatweaks@3.3.7, farmlanddropssoil@1.4.0, foodshelves@1.4.4, fromgoldencombs@1.8.1, gourmand@1.2.6, labeledtrunk@1.0.5, mobsradar@2.1.2, playerlist@2.1.4, claywheel@1.1.2, prospecttogether@1.4.0, rivers@3.2.0, scarecrow@1.6.1, stepupcontinued@0.0.1, usefulstuff17patch@1.0.0, stonebakeoven@1.1.4, storagecontroller@1.1.2, vanity@2.2.1, creative@1.20.0-rc.5, vsimgui@1.1.5, survival@1.20.0-rc.5, waypointtogether@1.0.1, wildfarmingrevival@1.2.9, configlib@1.3.13, helvehammerext@1.7.0, playercorpse@1.11.0, stonequarry@3.4.2, thriftysmithing@1.2.0System.NullReferenceException: Object reference not set to an instance of an object.   at Vintagestory.API.Common.ClientAnimator.calculateMatrices(Single dt) in VintagestoryApi\Common\Model\Animation\ClientAnimator.cs:line 294   at Vintagestory.Client.NoObf.SystemRenderEntities.OnBeforeRender(Single dt) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 49   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 188   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 824   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 161   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 695   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 670   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88   at OpenTK.Windowing.Desktop.GameWindow.Run()   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 334   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Server side:
[latest.log](https://github.com/user-attachments/files/18186943/latest.log)

**Comment by AreYSerious** [comment]
https://youtu.be/VNC2Ct4hovc



```
Game Version: v1.20.0-rc.5 (Unstable)
20.12.2024 23:06:12: Critical error occurred
Loaded Mods: advancedsmithing@1.3.0, aged@1.0.6, ancientarmory@1.0.6, arrowheadsrecovery@1.0.1, bettercrates@1.8.0-rc.4, betterloot@1.0.2, scrapblocks@1.1.0, bettershears@1.0.0, brickmold@1.2.0, canoemod@1.0.2, chiseltools@1.14.3, claycasting@1.2.2, darcesdrifters@1.0.0, easyelk@1.0.0, extrachests@1.8.0, fancysky@1.1.6, hideplayername@2.1.1, liberatedbeds@1.0.0, longtermfood@0.1.0, millwright@1.1.8, molds@0.1.3, nailsmold@1.0.2, oils@1.2.3, primitivesurvival@3.7.4, ripened_wild_crops@1.0.0, sortablestorage@2.2.8, stepfixelk@0.0.1, temporal_gears_stack@1.0.0, terraprety@5.0.5, translocatorengineeringredux@1.5.4, visibleore@1.0.1, game@1.20.0-rc.5, alchemy@1.6.41, animalcages@3.0.3, apegrapes@1.1.3, egocaribautomapmarkers@4.0.0, barreldough@2.0.0, betterfirepit@1.1.4, betterhewnfencegates@1.1.0, betterruins@0.4.1, butchering@1.7.3, carryon@1.7.4, commonlib@2.6.1, configureeverything@2.1.3, cooperativecombat@1.1.1, Crateful@1.2.8, danacancook@0.2.4, danatweaks@3.3.7, extrainfo@1.9.2, farmlanddropssoil@1.4.0, fixhandbookclutter@1.0.5, foodshelves@1.4.4, fromgoldencombs@1.8.1, gourmand@1.2.6, labeledtrunk@1.0.5, playerlist@2.1.4, claywheel@1.1.2, prospecttogether@1.4.0, rivers@3.2.0, scarecrow@1.6.1, stepupcontinued@0.0.1, usefulstuff17patch@1.0.0, stonebakeoven@1.1.4, storagecontroller@1.1.2, vanity@2.2.1, creative@1.20.0-rc.5, vsimgui@1.1.5, survival@1.20.0-rc.5, waypointtogether@1.0.1, wildfarmingrevival@1.2.9, configlib@1.3.13, dowsedinsalt@1.0.0, helvehammerext@1.7.0, playercorpse@1.11.0, stonequarry@3.4.2, thriftysmithing@1.2.0, statushudcont@2.1.2
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.ClientAnimator.calculateMatrices(Single dt) in VintagestoryApi\Common\Model\Animation\ClientAnimator.cs:line 294
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnBeforeRender(Single dt) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 49
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 188
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 824
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 161
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 695
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 670
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 92
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 334
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

**Comment by AreYSerious** [comment]
No crashes with the same world and this slightly reduced modlist

22.12.2024 19:06:19 [Notification] Mods, sorted by dependency: advancedsmithing, aged, ancientarmory, arrowheadsrecovery, bettercrates, betterloot, scrapblocks, bettershears, brickmold, canoemod, chiseltools, claycasting, darcesdrifters, easyelk, extrachests, fancysky, hideplayername, longtermfood, millwright, OfflineFoodNoSpoil, ripened_wild_crops, sortablestorage, stepfixelk, temporal_gears_stack, terraprety, translocatorengineeringredux, game, wildfarmingrevival, alchemy, animalcages, apegrapes, egocaribautomapmarkers, barreldough, betterfirepit, betterhewnfencegates, betterruins, butchering, carryon, commonlib, configureeverything, cooperativecombat, Crateful, danacancook, danatweaks, extrainfo, farmlanddropssoil, fixhandbookclutter, fromgoldencombs, gourmand, playerlist, claywheel, prospecttogether, stepupcontinued, usefulstuff17patch, storagecontroller, vanity, creative, vsimgui, survival, waypointtogether, configlib, dowsedinsalt, helvehammerext, playercorpse, stonequarry, th3essentials, thriftysmithing, statushudcont

**Comment by AreYSerious** [comment]
New but same looking issues from the crash

Running on 64 bit Windows 10.0.26100.0 with 32705 MB RAM
Game Version: v1.20.0-rc.5 (Unstable)
22.12.2024 19:23:19: Critical error occurred
Loaded Mods: advancedsmithing@1.3.0, aged@1.0.6, ancientarmory@1.0.6, arrowheadsrecovery@1.0.1, bettercrates@1.8.0-rc.4, betterloot@1.0.2, scrapblocks@1.1.0, bettershears@1.0.0, brickmold@1.2.0, canoemod@1.0.2, chiseltools@1.14.3, claycasting@1.2.2, darcesdrifters@1.0.0, easyelk@1.0.0, extrachests@1.8.0, fancysky@1.1.6, hideplayername@2.1.1, longtermfood@0.1.0, millwright@1.1.8, molds@0.1.3, nailsmold@1.0.2, oils@1.2.3, primitivesurvival@3.7.4, ripened_wild_crops@1.0.0, sortablestorage@2.2.8, stepfixelk@0.0.1, temporal_gears_stack@1.0.0, terraprety@5.0.5, translocatorengineeringredux@1.5.4, visibleore@1.0.1, game@1.20.0-rc.5, wildfarmingrevival@1.2.9, alchemy@1.6.41, animalcages@3.0.3, apegrapes@1.1.3, egocaribautomapmarkers@4.0.0, barreldough@2.0.0, betterfirepit@1.1.4, betterhewnfencegates@1.1.0, betterruins@0.4.2, butchering@1.7.3, carryon@1.7.4, commonlib@2.6.1, configureeverything@2.1.3, cooperativecombat@1.1.1, Crateful@1.2.8, danacancook@0.2.4, danatweaks@3.3.7, extrainfo@1.9.2, farmlanddropssoil@1.4.0, fixhandbookclutter@1.0.5, foodshelves@1.4.4, fromgoldencombs@1.8.1, gourmand@1.2.6, playerlist@2.1.4, claywheel@1.1.2, prospecttogether@1.4.0, rivers@3.2.0, scarecrow@1.6.1, stepupcontinued@0.0.1, usefulstuff17patch@1.0.0, storagecontroller@1.1.2, vanity@2.2.1, creative@1.20.0-rc.5, vsimgui@1.1.5, survival@1.20.0-rc.5, waypointtogether@1.0.1, configlib@1.3.13, dowsedinsalt@1.0.0, helvehammerext@1.7.0, playercorpse@1.11.0, stonequarry@3.4.2, thriftysmithing@1.2.0, statushudcont@2.1.2
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.MathTools.Cuboidd.Set(Cuboidf selectionBox) in VintagestoryApi\Math\Cuboid\Cuboidd.cs:line 107
   at Vintagestory.API.MathTools.AABBIntersectionTest.RayIntersectsBlockSelectionBox(BlockPos pos, BlockFilter filter, Boolean testCollide) in VintagestoryApi\Math\AABBIntersectionTest.cs:line 116
   at Vintagestory.Client.NoObf.SystemSoundEngine.scanReverbnessOffthread() in VintagestoryLib\Client\Systems\Audio\SoundEngine.cs:line 412
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

**Comment by digital-r** [comment]
Can confirm. University ruin in my world crashes my client too. Deeper i go - more frequent crashes i have.

System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.ClientAnimator.calculateMatrices(Single dt) in VintagestoryApi\Common\Model\Animation\ClientAnimator.cs:line 307
   at Vintagestory.API.Common.AnimatorBase.OnFrame(Dictionary`2 activeAnimationsByAnimCode, Single dt) in VintagestoryApi\Common\Model\Animation\AnimatorBase.cs:line 193
   at Vintagestory.API.Common.ClientAnimator.OnFrame(Dictionary`2 activeAnimationsByAnimCode, Single dt) in VintagestoryApi\Common\Model\Animation\ClientAnimator.cs:line 289
   at Vintagestory.API.Common.AnimationManager.OnClientFrame(Single dt) in VintagestoryApi\Common\Model\Animation\AnimationManager.cs:line 427
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnBeforeRender(Single dt) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 75
   at Vintagestory.API.Client.DummyRenderer.OnRenderFrame(Single deltaTime, EnumRenderStage stage) in VintagestoryApi\Client\API\IClientEventAPI.cs:line 83
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 194
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 816
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 868
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 740
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 170
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 695
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 670
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 334
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by DejFidOFF** [comment]
Same here
Running on 64 bit Windows 10.0.22631.0 with 81842 MB RAM
Game Version: v1.20.0-rc.6 (Unstable)
26.12.2024 16:17:53: Critical error occurred
Loaded Mods: aged@1.0.6, Allclasses@1.0.9, signs@1.0.2, bartender@1.0.2, bettercrates@1.8.0-rc.4, bigboards@1.0.0, chiseltools@1.14.4, ClaimsRadar@1.1.0, czechpatch@1.0.4, domesticanimaltrader@1.0.7, dinornithidae@1.0.5, sirenia@1.0.10, hangingoillamps@1.0.3, lumberjackone@1.0.1, millwright@1.1.8, mushroomtrader@1.0.3, Pirate@1.0.7, primitivesurvival@3.7.4, locustmod2@2.4.2, translocatorengineeringredux@1.5.4, game@1.20.0-rc.6, wildanimalstrader@1.0.6, xmastimecont@0.2.6, apelanterns@1.0.0, flags@1.1.3, bedspawnv2@1.3.0, betterruins@0.4.2, canmarket@0.4.1, carryon@1.8.0-pre.1, commonlib@2.6.1, composter@1.1.1, extrainfo@1.9.4, fromgoldencombs@1.8.1, gifty@1.0.0-rc.4, hudclockpatch@1.0.0, hydrateordiedrate@1.6.1, playerlist@2.1.5, pomnotes@0.7.3-rc.1, rifteye@0.4.0, SoundOfConfession@1.0.4, speedboat@1.0.0, stonebakeoven@1.1.4, th3dungeon@0.3.1, vanvar@6.0.7, creative@1.20.0-rc.6, vsserverpanel@0.1.5, survival@1.20.0-rc.6, wildfarmingrevival@1.3.3, woodstain@1.2.0, xlibpatch@1.0.1, cavebeacons@1.0.8, columns@1.1.0, em@3.0.0-pre.3, playercorpse@1.11.0, xskillspatch@1.0.4, moreroads@1.5.8
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.ClientAnimator.calculateMatrices(Single dt) in VintagestoryApi\Common\Model\Animation\ClientAnimator.cs:line 294
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnBeforeRender(Single dt) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 49
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 188
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 825
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 161
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 695
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 670
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 334
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 14.12.2024 21:21:43, Site = , Source = Application Error, Message = Název chybující aplikace: Vintagestory.exe, verze: 1.20.0.0, časové razítko: 0x66470000
Název chybujícího modulu: openal32.dll, verze: 1.23.0.0, časové razítko: 0x63dd31ad
Kód výjimky: 0x40000015
Posun chyby: 0x00000000000df046
ID chybujícího procesu: 0x0x7d74
Čas spuštění chybující aplikace: 0x0x1db4e6584a37fed
Cesta k chybující aplikaci: C:\Games\Vintagestory1.20rc1\Vintagestory.exe
Cesta k chybujícímu modulu: C:\Games\Vintagestory1.20rc1\Lib\openal32.dll
ID zprávy: 3f631b33-20b2-454b-9698-f49cd1e3f97e
Úplný název chybujícího balíčku: 
ID aplikace související s chybujícím balíčkem:  }
--------------
{ TimeGenerated = 12.12.2024 12:16:25, Site = , Source = Application Error, Message = Název chybující aplikace: Vintagestory.exe, verze: 1.20.0.0, časové razítko: 0x66470000
Název chybujícího modulu: openal32.dll, verze: 1.23.0.0, časové razítko: 0x63dd31ad
Kód výjimky: 0x40000015
Posun chyby: 0x00000000000df046
ID chybujícího procesu: 0x0x4ff0
Čas spuštění chybující aplikace: 0x0x1db4c87240ec53c
Cesta k chybující aplikaci: C:\Games\Vintagestory1.20\Vintagestory.exe
Cesta k chybujícímu modulu: C:\Games\Vintagestory1.20\Lib\openal32.dll
ID zprávy: 3595e8c0-0445-4e01-88b5-6c7cdb14ef47
Úplný název chybujícího balíčku: 
ID aplikace související s chybujícím balíčkem:  }
--------------
{ TimeGenerated = 09.12.2024 14:09:18, Site = , Source = Application Error, Message = Název chybující aplikace: Vintagestory.exe, verze: 1.20.0.0, časové razítko: 0x66470000
Název chybujícího modulu: openal32.dll, verze: 1.23.0.0, časové razítko: 0x63dd31ad
Kód výjimky: 0x40000015
Posun chyby: 0x00000000000df046
ID chybujícího procesu: 0x0x6974
Čas spuštění chybující aplikace: 0x0x1db4a3b6bcbaee4
Cesta k chybující aplikaci: C:\Games\Vintagestory1.20\Vintagestory.exe
Cesta k chybujícímu modulu: C:\Games\Vintagestory1.20\Lib\openal32.dll
ID zprávy: d97de1c8-38d9-4426-87a0-f79255ef6043
Úplný název chybujícího balíčku: 
ID aplikace související s chybujícím balíčkem:  }

**Comment by AreYSerious** [comment]
@DejFidOFF
@digital-r

Thank you very much for the crash logs will help the devs trouble shot that issue.

Our hope is currently at them taking a look at it here:

https://github.com/anegostudios/VintageStory-Issues/issues/4243

**Comment by AreYSerious** [comment]
> Can confirm. University ruin in my world crashes my client too. Deeper i go - more frequent crashes i have.
> 
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at Vintagestory.API.Common.ClientAnimator.calculateMatrices(Single dt) in VintagestoryApi\Common\Model\Animation\ClientAnimator.cs:line 307
>    at Vintagestory.API.Common.AnimatorBase.OnFrame(Dictionary`2 activeAnimationsByAnimCode, Single dt) in VintagestoryApi\Common\Model\Animation\AnimatorBase.cs:line 193
>    at Vintagestory.API.Common.ClientAnimator.OnFrame(Dictionary`2 activeAnimationsByAnimCode, Single dt) in VintagestoryApi\Common\Model\Animation\ClientAnimator.cs:line 289
>    at Vintagestory.API.Common.AnimationManager.OnClientFrame(Single dt) in VintagestoryApi\Common\Model\Animation\AnimationManager.cs:line 427
>    at Vintagestory.Client.NoObf.SystemRenderEntities.OnBeforeRender(Single dt) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 75
>    at Vintagestory.API.Client.DummyRenderer.OnRenderFrame(Single deltaTime, EnumRenderStage stage) in VintagestoryApi\Client\API\IClientEventAPI.cs:line 83
>    at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 194
>    at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 816
>    at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 868
>    at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 740
>    at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 170
>    at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 695
>    at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 670
>    at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
>    at OpenTK.Windowing.Desktop.GameWindow.Run()
>    at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 334
>    at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
>    at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
> 

Interesting bcs I saw someone in the stream that had the same issue in the opposite way. The higher he went in the university tower the more crashes he got.

**Comment by AreYSerious** [comment]
@digital-r
@DejFidOFF
@percussigant

![Screenshot_20241229_082830_Chrome.jpg](https://github.com/user-attachments/assets/28fec710-4268-48df-8aa6-9fc311ea392e)

Should be fixed with the latest version of primitive survival it was one entity having a broken animation.
