### ISSUE TITLE
[BUG]: Few white textures with a red question mark on it in some ruins

### ISSUE THREAD

**Issue by TripleJin-VS** [AreYSerious/betterruins#53]
### Mod Version

v0.4.2

### Game Version

v1.20.0-rc.5

### Platform

Windows

### SP/MP

Singleplayer

### Description

Having some white textures with red questionmark on some ruins, even after using /wgen regen 5
When approaching the texture it says right click to remove the decoration on it. Then the block will fall on the floor, as a white cube with the red "?" on it, and the block it was previously on will be back to normal. But when i pick the "?" block in inventory, as soon as i hover with the mouse on it the game will crash to desktop.

### Screenshots

![2024-12-24_14-42-35](https://github.com/user-attachments/assets/b8052c73-221b-449d-bda1-2037700f6b08)
![2024-12-24_14-42-54](https://github.com/user-attachments/assets/11a43e9c-2421-4629-9c91-e8cc4c4f5b2d)
![2024-12-24_14-45-03](https://github.com/user-attachments/assets/05a9a895-9488-4cd4-9dfc-5c92ba30bf26)

### Logs

Running on 64 bit Windows 10.0.26100.0 with 32678 MB RAM
Game Version: v1.20.0-rc.5 (Unstable)
24/12/2024 14:54:41: Critical error occurred
Loaded Mods: bettercrates@1.8.0-rc.4, bettersticks@1.2.0, bettertraders@0.0.7, bradyladder@1.0.0, chiseltools@1.14.4, combatoverhaul@0.0.101, domesticanimaltrader@1.0.7, flourbags@1.1.0, caninae@1.0.22, capreolinae@1.1.11, casuariidae@1.0.14, dinornithidae@1.0.5, manidae@1.0.7, pantherinae@1.1.15, rhinocerotidae@1.0.9, sirenia@1.0.10, hangingoillamps@1.0.3, instanddrifterdrops@1.1.0, millwright@1.1.8, mushroomtrader@1.0.3, natshumanskin@1.0.1, primitivesurvival@3.7.4, Sergsmetaltongs@1.1.0, sortablestorage@2.2.8, spyglass@0.5.2, stepfixelk@0.0.1, terraprety@5.0.6, translocatorengineeringredux@1.5.4, transparentglass@1.0.0, game@1.20.0-rc.5, wildanimalstrader@1.0.6, zoombuttonreborn@2.0.0, armory@0.0.30, betterruins@0.4.2, butchering@1.7.3, carryon@1.8.0-pre.1, chickenfeed@1.1.4, commonlib@2.6.1, extrainfo@1.9.4, foodshelves@1.4.4, hudclockpatch@1.0.0, maltiezcrossbows@0.5.11, maltiezfirearms@0.9.6, pigfeed@1.0.5, claywheel@1.1.2, stonebakeoven@1.1.4, traitacquirer@0.9.6, creative@1.20.0-rc.5, survival@1.20.0-rc.5, wildfarmingrevival@1.3.3, captureanimals@2.8.0, detailedanimals@0.3.3, playercorpse@1.11.0, stonequarry@3.4.2
Involved Harmony IDs: spyglass
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.BlockRockTyped.getRockType(String type) in VSSurvivalMod\Block\BlockRockTyped.cs:line 131
   at Vintagestory.GameContent.BlockRockTyped.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo) in VSSurvivalMod\Block\BlockRockTyped.cs:line 110
   at Vintagestory.API.Common.ItemSlot.GetStackDescription(IClientWorldAccessor world, Boolean extendedDebugInfo) in VintagestoryApi\Common\Inventory\ItemSlot.cs:line 476
   at Vintagestory.API.Client.GuiElementItemstackInfo.AsyncRecompose()
   at Vintagestory.API.Client.GuiElementItemstackInfo.SetSourceSlot(ItemSlot nowSlot, Boolean forceRecompose) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementItemstackInfo.cs:line 252
   at Vintagestory.Client.NoObf.HudMouseTools.OnMouseEnterSlot(ItemSlot slot) in VintagestoryLib\Client\Systems\Gui\Huds\HudMouseTools.cs:line 208
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerOnMouseEnterSlot(ClientMain game, ItemSlot slot) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 516
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.OnMouseMove(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Inventory\GuiElementItemSlotGridBase.cs:line 819
   at Vintagestory.API.Client.GuiComposer.OnMouseMove(MouseEvent mouse) in VintagestoryApi\Client\UI\GuiComposer.cs:line 504
   at Vintagestory.API.Client.GuiDialog.OnMouseMove(MouseEvent args) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 612
   at Vintagestory.Client.NoObf.GuiManager.OnMouseMove(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 433
   at Vintagestory.Client.NoObf.ClientMain.OnMouseMove_Patch0(ClientMain this, MouseEvent args)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.UpdateMousePosition() in VintagestoryLib\Client\ClientPlatform\Input.cs:line 111
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 127
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 334
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 130
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by AreYSerious** [comment]
Awesome thanks for the good bug report 👍

I will take a look at it after Christmas.

**Comment by AreYSerious** [comment]
Okay I generated 30 of those villages and could not replicate that issue maybe its a rare bug in worldgen I will reopen this if I can find anotherone with this issue. Thanks for the report tho.

Or if you can send me your Data folder with the save and Mods folder I could go to the location directly and take a look at the issue. If you could do that that would be epic. Let me know ty. Best would be a zip of your whole VintageStoryData folder if it doesnt contain to much stuff

**Comment by TripleJin-VS** [comment]
Thanks a lot for your time. Unfortunately i erased that world since; i had a white cube saved in my inventory and i couldn't remove it from my stash, hence i deleted it sorry... Weirdly enough, on the next world this bug never occured and everything is running perfectly - around a dozen of big ruins explored so far with roughly the same mods. 

Thanks again for your help, i guess my issue is closed then ?

Have a nice end of the year, and thanks for the amazing mod of course and the hard work.

**Comment by AreYSerious** [comment]
Aighty, thanks for letting me know. I wish you a nice end of the year and a happy new year later as well.

**Comment by bubblybre** [comment]
Hi! I wanted to let you know I’m running into the same rendering issue with the mod after updating the game to v1.20.0-rc.8. Some of the blocks in the ruins are showing up as white cubes with red question marks, and when I hover over them, it gives the “remove decor” option.

After reading this post, I generated a new world to see if it would fix the problem, but I’m still seeing the same thing even in a fresh world. I also tested disabling the mod, and when it’s turned off, I don’t see this issue on any of the ruins. I’ll attach some screenshots for reference. Let me know if there’s anything else I can do to help troubleshoot!

Thanks for all your hard work on this mod—it’s a favorite of mine!
![Bug1](https://github.com/user-attachments/assets/52863330-f53a-4a92-b56d-f536a68bf8b4)
![Bug2](https://github.com/user-attachments/assets/10585303-0acb-4e40-b4f9-ba49b4055df9)

**Comment by AreYSerious** [comment]
@bubblybre

The images do not work for me.

It would be best to also append the servermain and worldgen logs.
Thank you for the report.

**Comment by AreYSerious** [comment]
Does increasing the texture Atlas help with this problem.

I had someone with a similar problem and it didn't help but I want to make sure.

**Comment by AreYSerious** [comment]
It seems this issue if it happens only happens on village structures/formations. I will continue looking into it but not sure if there is a fix from our side possible.
I think this is a vanilla issue bcs I have seen it happen to vanilla villages aswell.

**Comment by Luiscavar** [comment]
Hi, just to let people and devs know, I figured out that some mods that add objects absolutely destroy the generation of structures, leaving the white blocks with red marks everywhere with no IDs and half-built buildings.
So far I noticed that it is impossible to run Better Ruins if you had:
- Decor Bazaar
- Kevins Furniture
Which is sad as I believe the presence of these mods add really cool features and objects to the game.
Not asking anyone to join the mods, but it would be nice if anyone could find what causes these generation errors and avoid the collisions.

Note: Spawning the structures with commands does not create this issue, but exploring the map and finding auto-generated ones would. Something in the way the mod auto-generates the structures crashes the constructions. Other mods could be causing the same issue, so I at least want to let the developers know about the issue.

**Comment by AreYSerious** [comment]
@Luiscavar

Did you try increasing your texture Atlas?

This is for the question mark issue related to too many new textures introduced.

The other one is probably related to village buildings having hiccups when generating.

Also images would be nice from the ruins with ?

**Comment by AreYSerious** [comment]
Okay yeah that's a completely new or special issue ty

**Comment by AreYSerious** [comment]
I recommend to regen or delete the chunks and hope that fixes it for you.

I will do some testing on those mods you listed on the weekend thanks for the input! I will keep yall updated here.

**Comment by AreYSerious** [comment]
@Luiscavar 

I just tested this on 1.20.5 rc3 and couldnt get any incorrect structures with the mods you named.... I will just say vanilla hopefully fixed some stuff with their improvements to perfomance in structure generation with those versions>

I also didnt get any ? blocks in village sets as of now. Will have to see if that version improved that.

**Comment by Luiscavar** [comment]
I am still in 1.20.3 due to mods compatibility, maybe there is a bug in that version. Thanks for the check, I will try to update once my modlist becomes compatible.

**Comment by ThothTheScribe** [comment]
Just to chime in, I only just ran into this bug following the 1.20.6 VS update and updating BetterRuins to 0.4.9. I've never had it occur before now. Don't know if this in any way helps other than to confirm that it is still a thing that seems to be happening.

**Comment by ThothTheScribe** [comment]
Follow-up: Nothing I did was able to correct the issue in the world it occurred in, but restarting the game and making a new world was able to generate ruins with no error textures. I suspect it's something getting messed up in the world's save data and persisting through attempted fixes.

**Comment by NicIAss** [comment]
https://github.com/anegostudios/VintageStory-Issues/issues/5600

If they fix this it will resolve some of the ? textures.

**Comment by NicIAss** [comment]
https://www.youtube.com/watch?v=NVq2tNkysgo

**Comment by VillanorSE** [comment]
I just had the same issue. Attached are logs. The zipped data folder is too large to upload.

[server-main.log](https://github.com/user-attachments/files/19764181/server-main.log)
[client-crash.log](https://github.com/user-attachments/files/19764182/client-crash.log)
[client-debug.log](https://github.com/user-attachments/files/19764183/client-debug.log)
[client-main.log](https://github.com/user-attachments/files/19764185/client-main.log)
[server-debug.log](https://github.com/user-attachments/files/19764184/server-debug.log)

**Comment by NicIAss** [comment]
> Currently having this issue. I have one of the blocks in my inventory and crash whenever I hover over it. Was there any way to fix this?

No fix for it yet. Waiting for vanilla to fix it.

Try to remove the item from your inventory by dropping it. Or dying then not picking it up.

No easy way I guess

**Comment by ForgottenPhoenix** [comment]
> > Currently having this issue. I have one of the blocks in my inventory and crash whenever I hover over it. Was there any way to fix this?
> 
> No fix for it yet. Waiting for vanilla to fix it.
> 
> Try to remove the item from your inventory by dropping it. Or dying then not picking it up.
> 
> No easy way I guess

I havent been able to drop it unfortunately, the crash is too fast. Will persist and see if I can find another way

**Comment by ForgottenPhoenix** [comment]
> > > Currently having this issue. I have one of the blocks in my inventory and crash whenever I hover over it. Was there any way to fix this?
> > 
> > 
> > No fix for it yet. Waiting for vanilla to fix it.
> > Try to remove the item from your inventory by dropping it. Or dying then not picking it up.
> > No easy way I guess
> 
> I havent been able to drop it unfortunately, the crash is too fast. Will persist and see if I can find another way

I ended up being able to dump my inventory using the in game commands. Lost the bag holding the affected item bu that was all :)

**Comment by StephenNorris** [comment]
I just had the ? blocks appear in 1.20.12 with BR 0.4.13.

I used /wgen regenr 1 to recreate the chunk, and the ruin (and the ? blocks) went away. I found another ruin nearby that was normal.
