### ISSUE TITLE
[BUG]: Failed registering item game:stackrandomizer-armor:

### ISSUE THREAD

**Issue by morggin** [AreYSerious/betterruins#56]
### Mod Version

BetterRuinsv0.4.2.

### Game Version

v1.20.0-rc.6 (Unstable)

### Platform

Linux

### SP/MP

Multiplayer

### Description

25.12.2024 00:37:47 [Error] Failed registering item game:stackrandomizer-armor:
25.12.2024 00:37:47 [Error] Exception: Attempted to register Item with code game:stackrandomizer-armor, but an item with such code already exists. Must use a unique code
   at Vintagestory.Server.ServerMain.RegisterItem(Item item) in VintagestoryLib\Server\ServerMain.cs:line 1762
   at Vintagestory.Server.ServerCoreAPI.RegisterItem(Item item) in VintagestoryLib\Server\API\ServerCoreAPI.cs:line 126
   at Vintagestory.ServerMods.NoObf.ModRegistryObjectTypeLoader.<LoadItems>b__14_0(List`1 variants) in VSEssentials\Loading\RegistryObjectTypeLoader.cs:line 239

### Logs

```Log```

**Comment by AreYSerious** [comment]
Interesting thanks for the bug report here 👍.

I will take a look from remote today and prob fix it after Christmas 😅

Thanks and have nice holidays.

**Comment by AreYSerious** [comment]
Okay seems that vanilla added a randomizer with the same name as betterruins so I will adjust that and patch onto the vanilla one. Will keep you updated when the update comes out but not earlier than tomorrow evening.

**Comment by AreYSerious** [comment]
Thank you very much I have fixed it and it will be in the next update.

Fixed with https://github.com/AreYSerious/betterruins/commit/66976676ba3cbe741f05f35c027aa06398fc5a0d
